[package]
name = "find-extract-html"
version = "0.2.4"
edition = "2021"

[lib]
name = "find_extract_html"
path = "src/lib.rs"

[[bin]]
name = "find-extract-html"
path = "src/main.rs"

[dependencies]
find-common = { path = "../../common" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

scraper = "0.21"
