[server]
url = "http://0.0.0.0:8765"
token = "local-dev-token-abc123"

[source]
name = "code"
paths = ["/home/jamie/code", "/mnt/data/cofig]

[scan]
exclude = [
    "**/.git/**",
    "**/node_modules/**",
    "**/target/**",
    "**/__pycache__/**",
    "**/.next/**",
    "**/dist/**",
    "**/.cache/**",
    "**/.tox/**",
    "**/.venv/**",
    "**/venv/**",
    "**/*.pyc",
    "**/*.class",
    "**/tmp/**",
    "**/temp/**",
]
max_file_size_kb = 1024
follow_symlinks = false
include_hidden = false

