[package]
name = "find-common"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow          = { workspace = true }
tracing         = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
